### ISSUE TITLE
Changing SET 2010 topology gives an undefined error

### ISSUE THREAD

**Issue by jashnani** [ni/niveristand-routing-and-faulting-custom-device#148]
Changing SET 2010 topology to anything other than BaseCard gives an unknown/undefined error:

![image](https://user-images.githubusercontent.com/29433053/68035127-ff496100-fc90-11e9-81c5-f498b6f3ce45.png)

Should the error be more descriptive?

**Reproduction Steps**

1.  Autodetect or Load an SET 2010 card in System Explorer
2. Change topoloy from BaseCard to anything else

**Comment by jashnani** [comment]
Is this happening because ChannelList (caps file) in other topologies is empty?

**Comment by jashnani** [comment]
Switching back to BaseCard gives the following error and endpoint configuration is now blank:

![image](https://user-images.githubusercontent.com/29433053/68035757-497f1200-fc92-11e9-91ae-4cd627495c3f.png)

**Comment by rtzoeller** [comment]
This is because the other topologies defined by the SET-2010 are not supported by SLSC Switch. The API they were designed to work with allowed for multiple topologies to be active, and we do not allow this. Individually, those topologies are not valid.

**Comment by rtzoeller** [comment]
That second error indicates that you have an old build. That was fixed in https://github.com/ni/niveristand-routing-and-faulting-custom-device/pull/139. Please test with the latest.

**Comment by jashnani** [comment]
I'm testing the latest build and it doesn't seem to have this fix.

**Comment by rtzoeller** [comment]
The changes are in master, so it looks like we just haven't had a good build since those changes went in 4 days ago. FYI @csjall

**Comment by Karl-G1** [comment]
Looks like this bug still exists. @rtzoeller to take a look.

**Comment by Karl-G1** [comment]
PR #162 fixed the inability to return to the 'good' topology. The other topologies that are invalid will still cause errors, but this is expected behavior.
